apiVersion: apps/v1
kind: Deployment
metadata:
  name: monservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monservice
  template:
    metadata:
      labels:
        app: monservice
    spec:
      containers:
        - image: dewguy20/monservice:1
          imagePullPolicy: IfNotPresent
          name: monservice
      restartPolicy: Always
